### ISSUE TITLE
Yoast Internal Link Checker 

### ISSUE THREAD

**Issue by PowerUser8852** [samiahmedsiddiqui/custom-permalinks#15]
Plugin stores the custom permalink value in the postmeta database with the meta_key custom_permalink.

Does not allow the Yoast Premium plug-in to show orphaned links properly. I will have several links pointing to an article but the article will still show as orphaned.

**Comment by samiahmedsiddiqui** [comment]
Hi @PowerUser8852 

Sorry for having delay in noticing this issue.

Does you still facing this issue or has it been fixed by Yoast SEO?

Regards,
Sami

**Comment by PowerUser8852** [comment]
Hi there, the issue has still not been fixed.

**Comment by samiahmedsiddiqui** [comment]
@PowerUser8852 Do you have development or staging site where i can see and fix this issue?
