### ISSUE TITLE
Non-existing posts end with index.php instead of 404

### ISSUE THREAD

**Issue by tgowing** [samiahmedsiddiqui/custom-permalinks#19]
We are using the Custom Permalinks plugin on our website (). We have a an articles page (/freedom-essays) where we list articles from the "freedom-essays" category.

When accessing /freedom-essays/article-slug-that-does-exist/ the post loads correctly, BUT, if we access a url like this:

/freedom-essays/article-slug-which-does-not-exist/

...the index.php file is loaded, which lists the recent posts that were created. Instead, we expect a 404 page to be loaded instead in this case.

Is it possible to fix this ?

Thanks very much for your time.

---

CP Version: **`1.4.0`**
WordPress Version: **`4.9.8`**

**Comment by samiahmedsiddiqui** [comment]
@tgowing Just do the following things.

1. Change Permalinks to the "Plain" from the Permalinks Settings Page.
2. Reset the permalink settings to as it was before following the point 1.
3. If it doesn't work then please check that your .htaccess file contains the default WordPress Rules. If not then please add them.

Most probably these steps will resolve your issues.

Regards,
Sami

**Comment by samiahmedsiddiqui** [comment]
@tgowing As per not getting any response, I am closing this issue. Please feel free to open a new one if you face any issue.

Thanks and Regards,
Sami
