### ISSUE TITLE
Getting 'Undefined Index' Error Message.

### ISSUE THREAD

**Issue by iSiddharthGiri** [samiahmedsiddiqui/custom-permalinks#21]
Hello!

I am using the Custom Permalinks Plugin on my website and from today, I started getting an error message:

`Notice: Undefined index: post_type in /wp-content/plugins/custom-permalinks/frontend/class-custom-permalinks-frontend.php on line 204`
`Notice: Undefined index: p in /wp-content/plugins/custom-permalinks/frontend/class-custom-permalinks-frontend.php on line 204`
`Notice: Undefined variable: query in /wp-includes/class-wp.php on line 244`
`Notice: Undefined variable: matches in /wp-includes/class-wp.php on line 247`

Please note that plugin is working fine but the problem is I get the above error message whenever I try to preview any post.

I have also tried to disable all the plugin except Custom Permalinks and also used Twenty Seventeen but still, I am getting the error message.

So, I hope to get a solution from you.

Thanks.

**Comment by samiahmedsiddiqui** [comment]
Hello @iSiddharthGiri 

Thank you for reaching out. As per your provided error logs i am assuming it is only happening on the Draft Post. Is that correct?

I don't think it is happening on the published posts for you.

By the way, which version of the plugin you are using?

Regards,
Sami

**Comment by iSiddharthGiri** [comment]
Hello!

>I don't think it is happening on the published posts for you.

No, I am getting this error whenever I try to preview any post(Published or Draft both).

> By the way, which version of the plugin you are using?

I am using the 1.4.0 version.

Thanks.

**Comment by abdoham213** [comment]
hello all, 

Have you fixed this problem? can you share the solution with me?

**Comment by samiahmedsiddiqui** [comment]
@abdoham213 I have already released the fix. Are you still having this issue? If yes, then can you please let me know what plugin version you are using and provide me the errors what you are getting?
