### ISSUE TITLE
Conflict with Classic Editor plugin

### ISSUE THREAD

**Issue by kick-point** [samiahmedsiddiqui/custom-permalinks#22]
Custom Permalinks appears to have a conflict with the Classic Editor plugin, causing the URL edit function to not be available when Classic Editor is active.

We ran some tests and found that the bug shows up even under the following conditions:

WordPress version: 5.0.3
Active theme: Twenty Nineteen
All plugins inactive except Custom Permalinks and Classic Editor
PHP version: 7.2.1

Deactivating Classic Editor immediately restores the URL edit function.

**Comment by samiahmedsiddiqui** [comment]
Hi @kick-point 

Thanks for reporting this issue and sorry for the delay in my response. I was on vacations and just started today to reply the emails.

I have quite long list of emails, making them reply at this moment and will start providing the fix ASAP for me. 

Please be patient, i will check your query and will back to you with some solution.

Thanks,
Sami
