### ISSUE TITLE
Got 404 Error when category custom permalink is part of post custom permalink

### ISSUE THREAD

**Issue by kevinmrl** [samiahmedsiddiqui/custom-permalinks#29]
Hello,

Got 404 Error when requesting post with custom permalink, I will provide steps to reproduce:

1. Go to Settings->Permalinks and ensure that:

- Selected Custom Structure with value “http://yourdomain.com/%category%/%postname%/”

- Category base value is “.”

2. Create category – Name: “My new category”, Slug: “my-new-category” and press Add New Category

3. Change category Custom Permalink from “my-new-category” to “new-category” and press Update

4. Change category slug from “my-new-category” to “new-category” and press Update

5. Create post – Title “My new category post”, add category “My new category” and Publish

6. Ensure that post URL now is “http://yourdomain.com/new-category/my-new-category-post/”

7. Go to that URL “http://yourdomain.com/new-category/my-new-category-post/” – here I got 404 error

The only thing what I found that WordPress is parsing this request like: category name is “new-category/my-new-category” and post name is “-post”. The it searches this post with slug “-post” and doesn’t find it.

When I deactivate Custom Permalinks plugin, everything works good.

Plugin version: 1.5.1
WordPress version: 5.2.1

**Comment by samiahmedsiddiqui** [comment]
Hi @kevinmrl Apologies for writing you after such a long time. I think, I have already fixed this issue in v1.7.1 as I am not able to generate this anymore but before it was generating. Can you please recheck So I can either dig into it if it still an issue or close this.

Thanks and Regards,
Sami
