### ISSUE TITLE
Permalink Breaks

### ISSUE THREAD

**Issue by houstona** [samiahmedsiddiqui/custom-permalinks#33]
The custom permalink has randomly changed on us sometimes.

It goes from this:

/products/food-conveyor/success-stories/bagged-olives

To this:

/products/food-conveyor/productsfood-conveyorproductsfood-conveyorsuccess-stories/bagged-olives

**Comment by houstona** [comment]
The permalinks changing on their own has happened once before this occurrence.

Here also some additional information on this:
WordPress version is: 5.4

**We are using the following plugins:**
Autoptimize	Version 2.6.2 by Frank Goossens (futtta)
Better Search Replace	Version 1.3.3 by Delicious Brains
Classic Editor	Version 1.5 by WordPress Contributors
Custom Permalinks	Version 1.5.1 by Sami Ahmed Siddiqui
Gravity Forms	Version 2.4.17 by rocketgenius
Gravity Forms Image In HTML	Version 1.0 by Ethan Piliavin
Hide YouTube Related Videos	Version 1.4.2 by SparkWeb Interactive, Inc.
iThemes Security Pro	Version 5.9.4 by iThemes
Mailgun	Version 1.7.1 by Mailgun
Official Facebook Pixel	Version 2.0.1 by Facebook
Redirection	Version 4.7.1 by John Godley
Schema App Advanced	Version 1.8.11 by Hunch Manifest
Schema App Structured Data	Version 1.15.1 by Hunch Manifest
Simple Custom Post Order	Version 2.4.9 by Colorlib
Smush	Version 3.6.1 by WPMU DEV
SSL Insecure Content Fixer	Version 2.7.2 by WebAware
String Locator	Version 2.3.1 by Clorith
Support Icon	Version 1.0
WP Sitemap Page	Version 1.6.2 by Tony Archambeau
Yoast SEO	Version 13.5 by Team Yoast

**Comment by houstona** [comment]
@samiahmedsiddiqui any news on this?

**Comment by samiahmedsiddiqui** [comment]
@houstona Sorry for my late response but I am still not able to generate your reported bug and none of the plugin seems to be conflicting that causing the issue.

Few questions to debug this issue:
- How often it happens? 
- Is it still happening for you?
- Is it happen with all the Permalinks customized with this plugin or some of them? If some of them then what's a difference in those posts and the other posts?

**Comment by houstona** [comment]
@samiahmedsiddiqui it has happened twice now. It hasn't happened since switching it back to the correct URL. It appears to only be pages that are affected so far.

**Comment by houstona** [comment]
@samiahmedsiddiqui this is the 3rd or 4th time it has happened now.

**Comment by samiahmedsiddiqui** [comment]
@houstona Issue is that I am not able to generate this issue on my end. If you are still facing this issue then I need your and the site owner help to debug this issue.

If you could help me so please provide me your any dev or staging site access where you are seeing this issue so I can review it.

**Comment by samiahmedsiddiqui** [comment]
@houstona As per not getting any response from more than a month, I am closing this issue. Please feel free to open a new one if you face any issue.

Thanks and Regards,
Sami
