### ISSUE TITLE
Error when editing/updating permalink

### ISSUE THREAD

**Issue by thgmourao** [samiahmedsiddiqui/custom-permalinks#35]
Hello Sammy. Greetings from Brazil

I'm experiencing some errors with the permalink.

After creating a page, or a post and publishing it and updating the content many times it works fine.... BUT when editing the permalink later, (let´s say days or weeks), it stops working.

I guess there´s a conflict with the Polylang plugin action as it happens ONLY in other languages (/pt/ or /es/). The English version of the website runs in the main domain (without /en/) and we do't have seen so far the same error.

Interesting to say is that the page simply doesn't work. Is doesn't even return a 404 page.

4 things I realized:

1) Sometimes it happens and other times it does NOT happens. I don't really see a pattern.

2) When it happens, if I set the page/post to DRAFT, when we click "view tour", the button right next to the permalink box,  the page opens properly and the permalink works. But if we publish and update it the link stops working again.

3) If we change the language of the post to English, and it will remove the /pt/ or the /es/ of the links, it WORKS. When we set it back to the proper language (and there's the addition of the /pt/ or /es/ to the permalink) again it STOPS working.

4) Our Wordpress is not the last version (there's a new one) but this was happening even before and everything was updated.

What have I tried and it didn't work:

- duplicate the post (with a plugin) - the new post has the same behaviour (is is set to draft, it works and when published not).
- if a create a new page and manually copy all the content to the new page and now put the permalink the way I want it works, but then is a whole new file, right?

If you have any ideas of how to fix, or even if there´s any procedure less laborous than creating a whole new page and manually copying all the content I'll be very thankful.

Thanks a lot.

Thiago

CP Version Version 1.5.1
WP Version 5.3.2 (there's a new version, I know, but that doesn't seem to be the problem, as it was already happening when everything was uodated
Polylang version  2.7.1 

(PS: I also sent an email on your form (website Contact Us). Sorry, only now I saw the option to post here the bug report.)

**Comment by samiahmedsiddiqui** [comment]
@thgmourao Sorry for the late reply. Can you please check this issue again with [this](https://github.com/samiahmedsiddiqui/custom-permalinks/releases/tag/v1.6.0-beta3) beta version? I have fixed couple of bugs that also contains conflicts with WPML.

I think those fixes should automatically fixes PolyLang issue, can you please recheck? If everything fixed for you then that would be great otherwise can you please provide me any built-in example on your dev or staging server that I can review.

**Comment by samiahmedsiddiqui** [comment]
@thgmourao As per not getting any response from than a month, I am closing this issue. Please feel free to open a new one if you face any issue.

Thanks and Regards,
Sami
