### ISSUE TITLE
Paged NextGen Galleries Broken with Custom Permalinks 1.62 

### ISSUE THREAD

**Issue by McYolic** [samiahmedsiddiqui/custom-permalinks#38]
Paged NextGen Galleries seem broken with Custom Permalinks 1.62.  Rolled back to Custom Permalinks Version 1.5.1 and that "fixed" the issue for now but would like to update the plugin without breaking galleries.

**Comment by samiahmedsiddiqui** [comment]
@McYolic Do you have any dev or staging server where you can update the plugin the plugin and provide the URL of it with Site access?

It will save my time to generate this issue.

**Comment by McYolic** [comment]
It's happening across multiple builds but here's a clean test install (Wordpress's default 2020 Theme) with everything fully updated - http://dev.shiskey.com/critter-gallery  

/wp-admin    admin   j%N31B4Qtl 

You'll see NexGens pagination along the bottom no longer works unless Custom Permalinks is rolled back.

**Comment by samiahmedsiddiqui** [comment]
@McYolic Thank you for providing the test install access with FTP. I have updated your comment and removed the access details from it for the security purpose.

**Comment by samiahmedsiddiqui** [comment]
@McYolic Thank you for your help and providing your website access. You can find couple of PHP errors in your test install log because of me so please ignore them.

I have fixed this issue and will release it tonight or tomorrow in `v1.6.3`.

**Comment by samiahmedsiddiqui** [comment]
@McYolic I have released alpha version before the official release of the `v1.6.3`, please use this version on your test install and verify that it is solving your issue or not. 

You can download the alpha version from here:
https://github.com/samiahmedsiddiqui/custom-permalinks/releases/tag/v1.6.3-alpha

**Comment by McYolic** [comment]
Seems to have done the trick. Updated to 1.6.3 alpha on several live professional builds as well as the dev link without issue - 
http://dev.shiskey.com/critter-gallery/

Thank you for continued support of this excellent plugin.

**Comment by samiahmedsiddiqui** [comment]
@McYolic Thank you for providing your feedback 😄 

If you like the plugin then please provide your valuable feedback to the WordPress Forum.
https://wordpress.org/support/plugin/custom-permalinks/reviews/?rate=5#new-post

and save this repo in your **Starred** Repos list.
