### ISSUE TITLE
Oembed links are not correctly handled

### ISSUE THREAD

**Issue by manuluyten** [samiahmedsiddiqui/custom-permalinks#39]
By default, Wordpress includes 2 oembed headers:
<link rel="alternate" type="application/json+oembed" AND <link rel="alternate" type="text/xml+oembed" 

When custom-permalinks is activated, the address is correctly replaced in the header. 
However, when opening the included oembed links, a json oembed_invalid_url 404 response is generated.
However, when opening the oembed address with the original URL, the response is correctly generated.

Example to reproduce:
original address: http://www.host.com/mycategory/mypost
custom permalink address: http://www.host.com/ThiIsMyPost

generated oembed in page headers:
<link rel="alternate" type="application/json+oembed" href="http://www.host.com/wp-json/oembed/1.0/embed?url=http%3A%2F%2Fwww.host.com%2Fmycategory%2Fmypost">
<link rel="alternate" type="text/xml+oembed" href="http://www.host.com/wp-json/oembed/1.0/embed?url=http%3A%2F%2Fwww.host.com%2Fmycategory%2Fmypost&amp;format=xml">

result from http://www.host.com/wp-json/oembed/1.0/embed?url=http%3A%2F%2Fwww.host.com%2Fmycategory%2Fmypost:
{"code":"oembed_invalid_url","message":"Not Found","data":{"status":404}}

result from the original address with custom permalinks activated
http://www.host.com/wp-json/oembed/1.0/embed?url=http%3A%2F%2Fwww.host.com%2Fmycategory%2Fmypost:
{"version":"1.0","provider_name":"host.com","provider_url":" ..........--remaining content removed--

**Comment by samiahmedsiddiqui** [comment]
Hi @manuluyten Sorry for writing back to you after a month and Thank you for reporting this issue.

I have fixed this issue and released an alpha version of the plugin that you can download from the Github for the testing purpose.
https://github.com/samiahmedsiddiqui/custom-permalinks/releases/tag/v2.0.0-alpha.1

Please test and let me know your feedback.

Thanks and Regards,
Sami

**Comment by samiahmedsiddiqui** [comment]
This issue was fixed in https://github.com/samiahmedsiddiqui/custom-permalinks/commit/cea6892c1f79582fa7273849d641e4749cc71d1c and will be relased in `v2.0.0`.
