### ISSUE TITLE
Quick Edit dialog shows/edits WP's built-in slug

### ISSUE THREAD

**Issue by RyanDwyer** [samiahmedsiddiqui/custom-permalinks#4]
In the WP admin, when I go to the Posts list and click Quick Edit on a post, the slug shown is the built-in WP slug. WP's built-in slug is not used when Custom Permalinks is installed. This causes confusion for our client.

If I make a PR that fixes this, will you accept it? Is this something you've looked into before?

**Comment by samiahmedsiddiqui** [comment]
@RyanDwyer Have you changed the permalink of the page? If yes,  WP's built-in slug doesn't be used. If you have not updated the page link manually then it can be different than the Permalink.

Please create the page and edited that page from the Quick Edit without changing anything in the Permalink field.

Let me know, your thoughts on it.

**Comment by RyanDwyer** [comment]
> Have you changed the permalink of the page? If yes, WP's built-in slug doesn't be used. If you have not updated the page link manually then it can be different than the Permalink.

Do you mean the other way around?

If I create a new page and edit the slug from the **quick edit dialog**, it will also change on the normal edit screen. I'm guessing this is because your plugin doesn't do anything with the quick edit dialog so it saves the built-in slug, and on the normal edit screen your plugin falls back to showing the built-in slug if there is no override.

If I create a new page and edit the slug from the **normal edit screen** then the slug in the quick edit dialog is not changed. Again, I'm guessing this is because your plugin doesn't do anything with the quick edit dialog.

> Please create the page and edited that page from the Quick Edit without changing anything in the Permalink field.

This works, but when the slug is then edited from the normal edit screen then the quick edit screen shows the old slug.

We can't tell our client to only edit the slug from only one of the quick edit screen or the normal edit screen. They should be able to use both interchangeably.

The issue is that the quick edit dialog always shows and edits the built-in WP slug, regardless of whether it has been overridden by your plugin.

**Comment by Fleuv** [comment]
Who got time to fix this issue?

**Comment by KatyLamb** [comment]
I have tried multiple times to fix the built in slug (which is coming up as (https://fingertipstyping.co.uk/transcription-services-2/)
I literally have no idea why its coming up as number 2 as there are no duplicates and the plugin doesn't allow me to change the built in slug.....any suggestions? Edit permalink and quick edit don't work. Thanks.
