### ISSUE TITLE
WP built in slug is unchangeable

### ISSUE THREAD

**Issue by KatyLamb** [samiahmedsiddiqui/custom-permalinks#42]
I have tried multiple times to fix the built in slug (which is coming up as (https://fingertipstyping.co.uk/transcription-services-2/)
I literally have no idea why its coming up as number 2 as there are no duplicates and the plugin doesn't allow me to change the built in slug.....any suggestions? Edit permalink and quick edit don't work. Thanks.

**Comment by samiahmedsiddiqui** [comment]
@KatyLamb when I hit https://fingertipstyping.co.uk/transcription-services-2/ it redirects me to https://fingertipstyping.co.uk/2017-now-thats-a-wrap/.

Have you resolved the issue or am I seeing something incorrect?

**Comment by samiahmedsiddiqui** [comment]
@KatyLamb Can you please provide so either I can fix this issue or close it.

**Comment by samiahmedsiddiqui** [comment]
@KatyLamb As per not getting any response, I am closing this issue. Please feel free to open a new one if you face any issue.

Thanks and Regards,
Sami
