### ISSUE TITLE
The problem is when there is a category in the structure of permalniks

### ISSUE THREAD

**Issue by Ercogx** [samiahmedsiddiqui/custom-permalinks#43]
Hi, I have a new error if I specify /% category% / in the permalink structure. When I create a new post and attach a child category to it, this post is not available and I get 404. If the category is not a child but the main one - then everything is ok

**Comment by samiahmedsiddiqui** [comment]
Hi @Ercogx I have changed the permalink structure to `/%category%/%postname%/`. Create a new Category with the name of **Parent Category** and then Create another Category with the name of **Child Category** under **Parent Category**.

After that, I have created a new post called **Test Post** and select **Child Category** so permalink becomes: `/parent-category/child-category/test-post/`

and works fine for me. Can you please describe how should I generate this problem on my end.

Thanks and Regards,
Sami

**Comment by samiahmedsiddiqui** [comment]
As per not getting any response, I am marking closing this issue.
