### ISSUE TITLE
(PHP 7.4) Deprecated: Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by codemonkeynorth** [samiahmedsiddiqui/custom-permalinks#44]
Hi @samiahmedsiddiqui 

Not a big issue as it can be turned off in WP_DEBUG, but just a heads up that the code is deprecated for PHP 7.4 in `class-custom-permalinks-frontend.php` Line 498 & 500

`Array and string offset access syntax with curly braces is deprecated`
https://github.com/samiahmedsiddiqui/custom-permalinks/blob/25a482a57a6ac8464ab927ffb60855dc6f47514c/frontend/class-custom-permalinks-frontend.php#L498

Thanks
J

**Comment by samiahmedsiddiqui** [comment]
Hi @codemonkeynorth 

You are referring 2 years back code. I have already fixed this issue in `v1.6.0`. You can check this in latest version of the plugin which is `1.7.1` and let me know if it's there.

Thanks and Regards,
Sami

**Comment by codemonkeynorth** [comment]
Hi @samiahmedsiddiqui 

Sorry I shall check version!

Thanks
J
