### ISSUE TITLE
admin delete action fails if WP_SITEURL is different to WP_HOME

### ISSUE THREAD

**Issue by codemonkeynorth** [samiahmedsiddiqui/custom-permalinks#45]
Hi,

I'm using bedrock,which sets up Wordpress like this
```
WP_HOME="http://test.local"
WP_SITEURL="http://test.local/wp"
```

so the admin is under `http://test.local/wp/wp-admin`

most things work ok but eg when I try a (bulk) delete action it tries to post to 
`http://test.local/wp/wp/wp-admin/admin.php?page=cp-post-permalinks`

note the `wp/` twice

thanks
J

**Comment by codemonkeynorth** [comment]
the problem is this line (for example)
https://github.com/samiahmedsiddiqui/custom-permalinks/blob/master/admin/class-custom-permalinks-post-types.php#L213

the `site_url` is `http://test.local/wp`
but the `request_uri` is `/wp/wp-admin/admin.php?page=cp-post-permalinks`

Yoast's implementation may work better for action urls? eg...

```
if ( is_multisite() ) {
	$action_url = network_admin_url( 'admin.php?page=wpseo_files' );
	$yform->admin_header( false, 'wpseo_ms' );
}
else {
	$action_url = admin_url( 'admin.php?page=wpseo_tools&tool=file-editor' );
}
```

https://github.com/Yoast/wordpress-seo/blob/043009c51bbd9a4e985ecc12c45b91fe9f291530/admin/views/tool-file-editor.php#L94

at minimum, using `admin_url` seems preferable?

**Comment by samiahmedsiddiqui** [comment]
Hi @codemonkeynorth Thank you for reporting this issue. I am going to completely change the way of this page. Once I am done with then I will ping you for the review at your end.

**Comment by samiahmedsiddiqui** [comment]
@codemonkeynorth Please check this issue with the latest version of the plugin. Hopefully, It won't be an issue anymore.
