### ISSUE TITLE
WP API is broken after saving taxonomy a couple of times

### ISSUE THREAD

**Issue by damianszewczyk** [samiahmedsiddiqui/custom-permalinks#46]
Hello!

I'd like to report to you an important bug which I found during using your plugin. After updating a few categories like the description, the WP API is crashed and returning 404.
To fix this, I have to re-save Permalinks of WP, then API is working as well.

Did you meet with a similar case? Or do you have an idea how to prevent this in the future?

P.S. the server is running on Nginx.

Regards
Damian

**Comment by samiahmedsiddiqui** [comment]
Hi @damianszewczyk 

I have replied on WordPress regarding your query that we never faced this issue before. Please provide some use-case scenario to us.

Also, please disable all the plugins and use default WordPress theme to debug whether it's plugin issue or some conflict with any other plugin.

Thanks,
Sami

**Comment by samiahmedsiddiqui** [comment]
As per not getting any response, I am closing this issue.
