### ISSUE TITLE
404 error when post/page custom permalink is part of category custom permalink

### ISSUE THREAD

**Issue by manuluyten** [samiahmedsiddiqui/custom-permalinks#49]
I am running all latest versions:
WP 5.6.1
custom-permalinks 1.7.1

Steps to reproduce
I have 1 page (or) post with 4 example custom permalink /faq/
I have 1 category with 4 example custom permalink /faq/category1/

The category will generate a 404 error.

**Comment by samiahmedsiddiqui** [comment]
Hi @manuluyten Sorry, I am not able to understand your issue. Can you please elaborate?

**Comment by manuluyten** [comment]
Dear @samiahmedsiddiqui ,

I will explain the casus with different words.

Try the following on a test environment:
- Create a page and define the address with custom-permalinks as: /faq/
- Create a category and define the address with custom-permalinks as /faq/category1/

The category will generate a 404 error.

I hope this helps.
Manu

**Comment by samiahmedsiddiqui** [comment]
@manuluyten Thank you for the detailed information. I have fixed the issue and it would be available in `v2.0.1` that would probably be released on **Aug 02** or **Aug 03**.

**Comment by manuluyten** [comment]
Much appreciated!


Manu Luyten
Movimento dell'Arte BV

***@***.*** ***@***.***>
www.movimentodellarte.be <https://www.movimentodellarte.be/>

+32 474 94 90 34

**Comment by samiahmedsiddiqui** [comment]
@manuluyten v2.0.1 has just released. Please update the version and let me know whether it fixes the issue for you or not.

**Comment by manuluyten** [comment]
I am in holiday modus at this point.

I will check and get back to you as soon as possible.

Manu Luyten
Movimento dell'Arte BV

***@***.*** ***@***.***>
www.movimentodellarte.be <https://www.movimentodellarte.be/>

+32 474 94 90 34
