### ISSUE TITLE
Redirects to home

### ISSUE THREAD

**Issue by davidperezgar** [samiahmedsiddiqui/custom-permalinks#52]
Hello! 
I'm using multisite with the plugin activated in a subsite. The url goes to home but in the tab bar you can still edit the page. 
How could I debug this issue in order to make it work?

**Comment by samiahmedsiddiqui** [comment]
Hi @davidperezgar

Can you please share the URLs that are redirecting to Home? Also, if you can share the login to the WP Site where the plugin is activated then it would be great.

NOTE: If you like to share the login then please share it on sami.siddiqui@yasglobal.com 

Regards,
Sami

**Comment by samiahmedsiddiqui** [comment]
@davidperezgar As we have already discussed this issue over email so I am closing this issue.

**Comment by davidperezgar** [comment]
Ok!
