### ISSUE TITLE
Trailing Slash No Longer Redirecting

### ISSUE THREAD

**Issue by eggzamummy** [samiahmedsiddiqui/custom-permalinks#54]
Recently, my site stopped ranking with google. I had someone look into it. They say, that because of the plugin, both versions of /page and /page/ are accessible. Normally wordpress would redirect /page to /page/. Google sees these as two separate urls, apparently not a good practice. Any chance you can guide me how to fix this?

**Comment by eggzamummy** [comment]
Just a quick note.  We upgraded from 1.7.1 to 2.2 and this is when the problem started.  We have reverted to 1.7.1 and it is working again.

**Comment by samiahmedsiddiqui** [comment]
@eggzamummy Thank you for reporting this issue. I have verified the issue and fixed it. Fix would be available in `v2.3.0`.
