### ISSUE TITLE
Notice: Undefined variable: site_url in custom-permalinks/admin/class-custom-permalinks-post-types-table.php on line 306

### ISSUE THREAD

**Issue by tbcan** [samiahmedsiddiqui/custom-permalinks#56]
Version: 2.3.0

It seems that $site_url is not defined yet at L360 of class-custom-permalinks-post-types-table.php when using with WPML

Who can let me know how to deal with it?

Here is capture:

<img width="1533" alt="Screen Shot 2021-09-29 at 10 55 47" src="https://user-images.githubusercontent.com/8665886/135200923-4eeff863-3ec2-4400-967d-c416feea3147.png">

Thanks in advance

**Comment by samiahmedsiddiqui** [comment]
@tbcan Thank you for reporting the issue. Fix applied and will be available in the `v2.4.0`.
