### ISSUE TITLE
Pending Status Preview Link

### ISSUE THREAD

**Issue by g-at-ieee** [samiahmedsiddiqui/custom-permalinks#58]
WP Version: 5.8
CP Version: 2.3.0

When a post is in pending status (pending review), the preview button and the view post button link to a live url page if the permalink has been changed.  In this case, the page returns a 404.  When the post is in draft mode, the view post and the preview button work as expected.

Looking at the code, the plugin only looks if the post is in draft, otherwise it treats it like a live post.

In custom-permalinks/includes/class-custom-permalinks-frontend.php on line 320:
`if ( 'draft' === $posts[0]->post_status ) {`
change to 
`if ( 'draft' === $posts[0]->post_status || 'pending' === $posts[0]->post_status ) {`

It is also present in custom-permalinks/includes/class-custom-permalinks-form.php
Line 464:
`if ( 'draft' === $post->post_status ) {`
change to 
`if ( 'draft' === $post->post_status || 'pending' === $post->post_status) {`

Line 878:
`if ( 'draft' === $post->post_status ) {`
change to 
`if ( 'draft' === $post->post_status || 'pending' === $post->post_status) {`

**Comment by samiahmedsiddiqui** [comment]
@g-at-ieee Thank you for reporting the issue and providing the suggestion. Changes applied and will be available in the `v2.4.0`.

**Comment by g-at-ieee** [comment]
Thank you.  Updated and it's working as intended.
