### ISSUE TITLE
Custom Permalinks removed from wordpress 

### ISSUE THREAD

**Issue by trancemanone** [samiahmedsiddiqui/custom-permalinks#69]
could you please explain why it was removed ?

**Comment by trancemanone** [comment]
is there a way to migrate the links profile to another plugin ?

**Comment by samiahmedsiddiqui** [comment]
@trancemanone I am communicating with WordPress plugin team to reopen it again, It would be opened in next few day. Till then you can download the plugin from here:
https://github.com/samiahmedsiddiqui/custom-permalinks/releases/latest

**Comment by trancemanone** [comment]
Any update ?

**Comment by samiahmedsiddiqui** [comment]
@trancemanone Plugins was removed for violating with **GDPR** which was fixed but Now, the WordPress plugin Security Team is asking to resolve few other issues that is taking time with my other priority tasks. I cannot confirm the time when it will be resumed on wordpress.org.
