### ISSUE TITLE
Custom Permalinks removed from wordpress

### ISSUE THREAD

**Issue by trancemanone** [samiahmedsiddiqui/custom-permalinks#70]
could you please explain why it was removed ?
is there a way to migrate the links profile to another plugin ?

You have mentioned that it will take few days its been 3 weeks.

**Comment by samiahmedsiddiqui** [comment]
@trancemanone It was removed for violating with **GDPR** which was fixed but Now, the WordPress plugin Security Team is asking to resolve few other issues that is taking time with my other priority tasks. I cannot confirm the time when it will be resumed on wordpress.org.
