### ISSUE TITLE
“http//” is added in front of permalinks

### ISSUE THREAD

**Issue by mknecht** [samiahmedsiddiqui/custom-permalinks#71]
After (automatically) upgrading to 2.5.0, a colleague and I noticed when editing different pages that on saving the string “http//” was added in front of the permalink. This breaks viewing the page. Also, the content of both our pages were overwritten by the same content of a completely unrelated page. 

Note, there is no colon in this “http//”, and no “s” for “https”—maybe that helps troubleshoot.

Restoring the previous version didn't work: whenever we saved, the permalink got prefixed again and the content was overwritten again. If you saved / restored multiple times, we got multiple “http//” prefixes.

After downgrading to 2.4.0 we could remove the prefix from the permalink, save the page, and then restore the old content.

WordPress 6.1.1 running Divi, on PHP 8.0.24

**Comment by samiahmedsiddiqui** [comment]
@mknecht Thank you for reporting this issue. It is fixed in v2.5.1, please verify at your end.

**Comment by mknecht** [comment]
Yup, saw, thanks so much! Will test v2.5.2 tomorrow.

**Comment by mknecht** [comment]
Upgraded to v2.5.2, tested around and all seems fine. Thanks a lot for the quick fix!
