### ISSUE TITLE
Can the plugin be kept upgraded?

### ISSUE THREAD

**Issue by wild2008** [samiahmedsiddiqui/custom-permalinks#85]
This plugin has been working well before, as it says, easy to use. 

But it has not been updated for two years, especially in the latest WordPress V6.5.4, some of its functions do not work, such as not being able to delete existing entries in Dashboard > Custom Permalinks > Post Types Permalinks. 

I hope the plugin author can fix this problem, thank you very much!

**Comment by samiahmedsiddiqui** [comment]
@wild2008 I am going to take a look and will release the updated version soon.

**Comment by samiahmedsiddiqui** [comment]
@wild2008 I have released a new version yesterday, please update the plugin and test the issue. I have tried to generate but doesn't found the issue you reported in the latest version of the plugin.

**Comment by wild2008** [comment]
@samiahmedsiddiqui Thanks for the great work. I will test it soon. Wish you all the best.
